services:
  backend:
    image: ${BACKEND_IMAGE:-fxdashboard-backend:local}
    build:
      context: ./backend
      args:
        INSTALL_MSSQL_ODBC: "true"
    container_name: fx-backend
    volumes:
      - ./data:/app/data # Database SQLite
      - ./backend/migrate_sksmrt.py:/app/migrate_sksmrt.py
      - ./backend/migrate_to_sqlite.py:/app/migrate_to_sqlite.py
      - ./backend/migrate_oslsrg_server.py:/app/migrate_oslsrg_server.py
      - ./backend/verify_all.py:/app/verify_all.py
      - ./backend/verify_sksmrt.py:/app/verify_sksmrt.py
    networks:
      - fxdb-net
    environment:
      - PORT=4000
      - DB_DIR=/app/data
      - TZ=Asia/Jakarta
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE:-fxdashboard-frontend:local}
    build: ./frontend
    container_name: fx-frontend
#    ports:
#      - "80:80"
    networks:
      - fxdb-net
    depends_on:
      - backend
    restart: always

networks:
  fxdb-net:
    external: true # Pastikan network ini sudah dibuat di server
