version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fx-backend
    volumes:
      - ./data:/app/data # Tempat menyimpan database SQLite
    networks:
      - density-net
    environment:
      - PORT=4000
      - DB_DIR=/app/data
    restart: always

  frontend:
    build: ./frontend
    container_name: fx-frontend
    ports:
      - "80:80"
    networks:
      - density-net
    depends_on:
      - backend
    restart: always

networks:
  density-net:
    external: true # Pastikan network ini sudah dibuat di server
